name: Build and Upload Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  DOTNET_VERSION: '9.0.x'
  CONFIGURATION: 'Release'

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          # - os: ubuntu-latest
          #   rid: linux-x64
          # - os: macos-latest
          #   rid: osx-x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore src/LiteRP.slnx

    - name: Build
      run: dotnet build src/LiteRP.slnx --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Publish
      run: >
        dotnet publish src/LiteRP.WebApp/LiteRP.WebApp.csproj
        -c ${{ env.CONFIGURATION }}
        -r ${{ matrix.rid }}
        -o ./publish
        -p:PublishSingleFile=true
        -p:PublishTrimmed=false
        -p:SelfContained=true
        
    - name: Compress artefact
      run: 7z a LiteRP-${{ matrix.rid }}.zip ./publish/*
    
    - name: Upload artefact
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.rid }}
        path: LiteRP-${{ matrix.rid }}.zip
  
  release:
    name: Draft GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: -o CHANGELOG.md
          
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: "LiteRP ${{ steps.vars.outputs.version }}"
          draft: false
          prerelease: false
          body_path: CHANGELOG.md
          files: artifacts/*/*.zip